# Generated by Django 5.1 on 2024-08-10 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='feature_image',
            field=models.ImageField(blank=True, null=True, upload_to='clinic_images/'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='working_hours',
            field=models.CharField(choices=[('09:00-17:00', '9:00 AM - 5:00 PM'), ('10:00-18:00', '10:00 AM - 6:00 PM'), ('11:00-19:00', '11:00 AM - 7:00 PM')], max_length=255),
        ),
    ]
